### ISSUE TITLE
ConcurrentModificationException in the GameRoomManager

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/backend#201]
Ein Team ist beim Trainieren ihres Clients auf einen Fehler im Server gestossen. Der Server beendet sich mit folgender Fehlermeldung:

```
18:13:54 ERROR sc.networking.clients.XStreamClient - Unknown Communication Error
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at sc.server.gaming.GameRoomManager.joinOrCreateGame(GameRoomManager.java:156)
        at sc.server.Lobby.onRequest(Lobby.kt:65)
        at sc.server.network.Client.notifyOnPacket(Client.java:93)
        at sc.server.network.Client.onObject(Client.java:230)
        at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:115)
        at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Xerus2000** [comment]
Das Problem erscheint mir, dass zwar alle einzelnen Methoden im `GameRoomManager` synchronized sind, aber es können immer noch zwei verschiedene Methoden gleichzeitig den state verändern. 
Ich würde fast sagen, dass der GameRoomManager auf seinem eigenen Thread operieren sollte, sodass immer nur eine Sache gleichzeitig passiert.

**Comment by SKoschnicke** [comment]
Benutzt der Server denn ueberhaupt mehrere Threads?

**Comment by Xerus2000** [comment]
Naja, wahrscheinlich um mit mehreren Clients gleichzeitig kommunizieren zu können. Damit der obige Fehler passiert, muss irgendwo ein Thread die `rooms` verändert haben während der Iterator aktiv war.

**Comment by SKoschnicke** [comment]
Ja, klingt plausibel. Dann also den GameRoomManager in einem eigenen Thread und die anderen Threads kommunizieren per message passing damit? Klingt nach einer groesseren Aenderung...

**Comment by Xerus2000** [comment]
Jup, hab ich so gedacht. Ja, das ist ne größere Änderung, aber ich weiß nicht wie man es sonst wirklich sicher machen kann.

**Comment by Xerus2000** [comment]
Vielleicht können wir da auch ein Kotlin pattern verwenden: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/actor.html
Ein Actor ist so ziemlich das wovon wir bisher geredet haben. Er empfängt Nachrichten und sendet welche aus. Und die return value von so ziemlich jeder an die Clients gerichteten Methode ist ja eine Message.

**Comment by SKoschnicke** [comment]
Ich bin mir nicht sicher, aber ich glaube, dass der GameRoomManager gar nicht direkt mit den Clients kommuniziert. Aber den koennten wir als Actor modellieren, ja.

**Comment by Xerus2000** [comment]
Naja indirekt über die Lobby halt. Aber die leitet auch nur die Nachrichten hin und die Antworten zurück ^^
![image](https://user-images.githubusercontent.com/13354331/52331941-abf3fc00-29f9-11e9-9284-51c3aaf105ea.png)

**Comment by SKoschnicke** [comment]
Und die Lobby existiert doch auch nur einmal im Server.

![2019-02-06-103346_1487x1008](https://user-images.githubusercontent.com/105162/52332399-caa6c280-29fa-11e9-94e0-31759f5736a7.jpg)

**Comment by Xerus2000** [comment]
> Und die Lobby existiert doch auch nur einmal im Server.

Das ist ein typischer pitfall. Nur 

Ich frage mich auch gerade, wie viel Sinn es überhaupt macht den GameManager und ClientManager von der Lobby zu separieren, weil die ja trotzdem ziemlich eng gecoupled sind.

**Comment by SKoschnicke** [comment]
>> Und die Lobby existiert doch auch nur einmal im Server.

> Was soll uns das sagen?

Ich dachte, wenn die Lobby nur einmal existiert, koennen da ja nicht mehrere Aufrufe parallel durch. Aber es geht darum, dass von mehreren Threads durchaus parallel auf die eine Lobby zugegriffen werden kann. Verstehe.

Die hohe Separierung ist eine Altlast. In den meisten Faellen kann man da was zusammenlegen.
