### ISSUE TITLE
onGameOver throws exception

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/backend#278]
When the handler in AbstractClient is not set, a GameOver throws an exception, although the case of a not initialized handler should be tested and handled gracefully.

```
kotlin.UninitializedPropertyAccessException: lateinit property error has not been initialized
	at sc.plugin2021.AbstractClient.onGameOver(AbstractClient.kt:129)
	at sc.networking.clients.LobbyClient.onGameOver(LobbyClient.java:140)
	at sc.networking.clients.LobbyClient.onObject(LobbyClient.java:89)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:113)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by anarchuser** [comment]
What should happen when trying to access a non-initialised handler?

**Comment by SKoschnicke** [comment]
https://github.com/CAU-Kiel-Tech-Inf/server/blob/edc99c9311085a3cf537ae5836af76a8ce015d8e/plugin/src/client/sc/plugin2020/AbstractClient.java#L163-L165

I think it is already tried to do the right thing: Not calling the handler if no handler is set.

**Comment by anarchuser** [comment]
https://github.com/CAU-Kiel-Tech-Inf/server/blob/edc99c9311085a3cf537ae5836af76a8ce015d8e/plugin/src/client/sc/plugin2021/AbstractClient.java#L128-L130

Should be the equivalent in the Blokus AbstractClient.
I'll check why it isn't working

**Comment by anarchuser** [comment]
What exactly did you do to get this error?

**Comment by SKoschnicke** [comment]
Start the GUI with the getPossibleMoves method active in ClientController.kt. Then start a game by clicking on the "Start Client" button. Because the getPossibleMoves method will error, the client will leave the game and the server sends a gameover event, which leads to this error in the other client.

**Comment by anarchuser** [comment]
Is this still valid?

**Comment by xerus2000** [comment]
Since having no handler is a valid state, the variably should be nullable rather than `lateinit` - the latter is something to very rarely use, usually for dependency injection.

**Comment by xerus2000** [comment]
If there is no use-case for having no handler, set it as constructor parameter. Either way, no lateinit and unexpected behavior ;)

**Comment by xerus2000** [comment]
fd60e793 should solve this
