### ISSUE TITLE
Task ':plugin:doc' fails on Windows and MacOS

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/backend#280]
So when I tried testing it on macOS, `.gradlew run`, `.gradlew deploy` etc. all fail at the task `:plugin:doc` with

```
Gradle could not start your build.
> Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory '/.gradle' when creating directory '/.gradle/6.5/fileHashes'
```

I guess this is just some misconfigured pathing? But why is it trying to access 6.5 as the used version of gradle wrapper is 6.3? When bumping the used version to 6.5 or 6.6 nothing changes.

Btw. task `:doc` fails as well

**Comment by xerus2000** [comment]
You mean `./gradlew run`, right?

**Comment by xerus2000** [comment]
I have no immediate idea how to fix this because I don't know what is going on. Please run with `--info --stacktrace` and post everything :)

**Comment by Yasamato** [comment]
Okay, so I first ran `./gradlew clean` to make it a clean process and this is the output of `./gradlew :plugin:doc --info --stacktrace`: [log.txt](https://github.com/CAU-Kiel-Tech-Inf/server/files/5147572/log.txt)

I tried this with jdk 8, 11 and 14. there is no difference in the logs besides the version numbers of the java-jdk (according to [diff](https://man7.org/linux/man-pages/man1/diff.1.html))

**Comment by xerus2000** [comment]
```
Task ':plugin:doc' is not up-to-date because:
  Task has failed previously.
```

Hmm, `clean` scheint nicht ganz geklappt zu haben. Versuch nochmal `clean`, dann lösche die `.gradle` und `build` Ordner komplett und schau ob mehr infos kommen.

**Comment by Yasamato** [comment]
It seems `clean` doesn't delete `.gradle`-folder but `build`. So running again results in: [log.txt](https://github.com/CAU-Kiel-Tech-Inf/server/files/5149305/log.txt)

**Comment by Yasamato** [comment]
It seems under Windows I am now unable to build as well with the recent changes, with the same clean freshly pulled state from master and no `.gradle` or any `build` directory, running `gradlew :plugin:doc --info --stacktrace` returns: [log.txt](https://github.com/CAU-Kiel-Tech-Inf/server/files/5182859/log.txt)

Results under MacOS are currently unchanged

**Comment by xerus2000** [comment]
Ok, habs reproduziert

**Comment by xerus2000** [comment]
Auf dem dokka updated branch:
```
* What went wrong:
Execution failed for task ':plugin:doc'.
> Metaspace
```
lel

**Comment by xerus2000** [comment]
Oof, looks like we need to update dokka to 1.4 so that it works with JDK 11: https://github.com/Kotlin/dokka/issues/294
I've already tried that, but it's a hassle.

**Comment by xerus2000** [comment]
Superseded by #342, use JDK 8 until then.
