### ISSUE TITLE
MoveMistakes don't tell who violated

### ISSUE THREAD

**Issue by anarchuser** [CAU-Kiel-Tech-Inf/backend#320]
It could have a method taking a Team or Color and return a message saying who violated how, i.e.:
```
MoveMistake.WRONG_COLOR.toString() shouldBe "Die Farbe des Zuges ist nicht an der Reihe"
MoveMistake.WRONG_COLOR.toString(Color.RED) shouldBe "Farbe Rot ist aktuell nicht an der Reihe"
```

Related to https://github.com/CAU-Kiel-Tech-Inf/gui/issues/7

**Comment by anarchuser** [comment]
Actually, there is probably no need for the first method; thus, it makes more sense to give MoveMistakes the color as property and change the first method into documentation

**Comment by xerus2000** [comment]
I would like to prevent coupling code that doesn't have to be coupled, i.e. not add the color as property.

**Comment by anarchuser** [comment]
seems reasonable.
I'm going to rework this anyways, though - It probably makes sense to construct GameLogicExceptions with MoveMistakes and Moves (the latter already contains information on the color, anyways)
