### ISSUE TITLE
getPossibleMoves seems to not calculate every possible move

### ISSUE THREAD

**Issue by anarchuser** [CAU-Kiel-Tech-Inf/backend#325]
In the following GameState, Green's turn, Green is supposed to be able to make a move; yet neither of the two remaining pieces can be placed on the given Board:
![image](https://user-images.githubusercontent.com/5949896/98530894-d1253680-227f-11eb-855d-c15aa2a212d4.png)

**Comment by nikohass** [comment]
I think the green Z-Shaped piece can be placed at the corner of the green Pento-V when it’s rotated the right way. Beneath and left of the red Pento-U.

**Comment by anarchuser** [comment]
oh, damn, you're right
I spent, like, 10 minutes trying to figure this out
