### ISSUE TITLE
Does gamestate.clone() work properly

### ISSUE THREAD

**Issue by TiLuHa** [CAU-Kiel-Tech-Inf/backend#346]
Using gamestate.clone() in the simple client logic doesn't lead to any compile errors. But running this client leads to an interesting exception see attachment.
![Screenshot_20201204_223920](https://user-images.githubusercontent.com/36930978/101217530-cc3a8380-3681-11eb-96be-2e7babf4085b.png)
![2](https://user-images.githubusercontent.com/36930978/101217597-f1c78d00-3681-11eb-9d58-5d7c63d14ba4.png)

**Comment by xerus2000** [comment]
Fixedc in #356
