### ISSUE TITLE
Have `round` and `turn` only in one place

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/backend#354]
Just realized that we track `round` and `turn` in both GameState and Game, yikes... Another issue for another day...

_Originally posted by @xerus2000 in https://github.com/CAU-Kiel-Tech-Inf/backend/issues/340#issuecomment-759548247_

**Comment by anarchuser** [comment]
Plus, `round` is directly calculated from `turn`

**Comment by xerus2000** [comment]
Hm, if I remove it from the Game, then it is hardly a `RoundBasedGameInstance` anymore ^^

**Comment by anarchuser** [comment]
rename it to `TurnBasedGameInstance`, then? ^^

**Comment by xerus2000** [comment]
it doesn't do any turn tracking anymore
