### ISSUE TITLE
GameState.clone() doesn't clone undeployedPieceShapes

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/backend#377]
`GameState.blueShapes`, `.redShapes` etc. are always initialized to `PieceShape.values().toMutableSet()` and not cloned when using `GameState.clone()`.

 
 
Initialization of `.blueShapes`, `redShapes` etc.:
https://github.com/CAU-Kiel-Tech-Inf/backend/blob/be14c0137457299602f024b74bd3796315faf75c/plugin/src/shared/sc/plugin2021/GameState.kt#L42-L45

Constructor called by `.clone()`:
https://github.com/CAU-Kiel-Tech-Inf/backend/blob/be14c0137457299602f024b74bd3796315faf75c/plugin/src/shared/sc/plugin2021/GameState.kt#L40

**Comment by xerus2000** [comment]
Fixed in #379
