### ISSUE TITLE
Turn-count is not increased if colors are skipped because they can't place a piece anymore

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/backend#388]
Was already tried to fix with https://github.com/CAU-Kiel-Tech-Inf/backend/commit/49676b64cf0ca56a784bb9653e59bdcdd59ad3f2

But seems to still occur: https://discordapp.com/channels/233577109363097601/417643295552831488/810190757180735558

**Comment by xerus2000** [comment]
Fixed in #391
